### ISSUE TITLE
"-" operator changes names between Week 2 and Week 3

### ISSUE THREAD

**Issue by retop56** [nlsandler/write_a_c_compiler#26]
Attached screenshots can be found below.

In week 2, the "-" operator is referred to as the "negation" operator, while in week 3 it's referred to as the "minus" operator. Is the difference intentional, and if so, why?

 Thank you for creating this series of blogposts and the accompanying test suite. Looking forward to the release of the book!

![Screenshot 2023-11-26 121220](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/f8eae338-8911-4a1b-8976-f389d304e6bf)
![Screenshot 2023-11-26 121316](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/7c0b9b51-3968-498d-b93c-725f0e3cbde5)

**Comment by nlsandler** [comment]
The difference isn't intentional. I generally use "minus" when talking about the binary operator and "negation" when talking about the unary operator - but the token is the same in both chapters, so strictly speaking it should have the same name. However, I'm probably not going to fix this since I'm no longer actively working on these blog posts - I'll still fix errors in these posts but generally not wording inconsistencies and the like.

But thanks for reporting this, and for the kind words about the series!
